// Code generated by protoc-gen-go.
// source: newapi.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	newapi.proto
	test.proto

It has these top-level messages:
	BidRequest
	App
	StaticInfo
	UserPermission
	Device
	UdId
	Version
	Gps
	User
	AdSlot
	Size
	Content
	Meta
*/
package main

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Type int32

const (
	Type_ACCESS_FINE_LOCATION Type = 1
	Type_CAMERA               Type = 2
	Type_RECORD_AUDIO         Type = 3
)

var Type_name = map[int32]string{
	1: "ACCESS_FINE_LOCATION",
	2: "CAMERA",
	3: "RECORD_AUDIO",
}
var Type_value = map[string]int32{
	"ACCESS_FINE_LOCATION": 1,
	"CAMERA":               2,
	"RECORD_AUDIO":         3,
}

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}
func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (x *Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Type_value, data, "Type")
	if err != nil {
		return err
	}
	*x = Type(value)
	return nil
}

type Status int32

const (
	Status_UNKNOWN  Status = 0
	Status_ACCEPTED Status = 1
	Status_REFUSED  Status = 2
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACCEPTED",
	2: "REFUSED",
}
var Status_value = map[string]int32{
	"UNKNOWN":  0,
	"ACCEPTED": 1,
	"REFUSED":  2,
}

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}
func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (x *Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Status_value, data, "Status")
	if err != nil {
		return err
	}
	*x = Status(value)
	return nil
}

type Os int32

const (
	Os_ANDROID Os = 1
	Os_IOS     Os = 2
)

var Os_name = map[int32]string{
	1: "ANDROID",
	2: "IOS",
}
var Os_value = map[string]int32{
	"ANDROID": 1,
	"IOS":     2,
}

func (x Os) Enum() *Os {
	p := new(Os)
	*p = x
	return p
}
func (x Os) String() string {
	return proto.EnumName(Os_name, int32(x))
}
func (x *Os) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Os_value, data, "Os")
	if err != nil {
		return err
	}
	*x = Os(value)
	return nil
}

type Orientation int32

const (
	Orientation_LAND Orientation = 1
	Orientation_PORT Orientation = 2
)

var Orientation_name = map[int32]string{
	1: "LAND",
	2: "PORT",
}
var Orientation_value = map[string]int32{
	"LAND": 1,
	"PORT": 2,
}

func (x Orientation) Enum() *Orientation {
	p := new(Orientation)
	*p = x
	return p
}
func (x Orientation) String() string {
	return proto.EnumName(Orientation_name, int32(x))
}
func (x *Orientation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Orientation_value, data, "Orientation")
	if err != nil {
		return err
	}
	*x = Orientation(value)
	return nil
}

type Sensor int32

const (
	Sensor_ACCELEROMETER          Sensor = 1
	Sensor_GYROSCOPE              Sensor = 4
	Sensor_GYROSCOPE_UNCALIBRATED Sensor = 16
	Sensor_LIGHT                  Sensor = 5
	Sensor_LINEAR_ACCELERATION    Sensor = 10
	Sensor_PRESSURE               Sensor = 6
	Sensor_PROXIMITY              Sensor = 8
	Sensor_RELATIVE_HUMIDITY      Sensor = 12
	Sensor_STEP_DETECTOR          Sensor = 18
	Sensor_TEMPERATURE            Sensor = 7
)

var Sensor_name = map[int32]string{
	1:  "ACCELEROMETER",
	4:  "GYROSCOPE",
	16: "GYROSCOPE_UNCALIBRATED",
	5:  "LIGHT",
	10: "LINEAR_ACCELERATION",
	6:  "PRESSURE",
	8:  "PROXIMITY",
	12: "RELATIVE_HUMIDITY",
	18: "STEP_DETECTOR",
	7:  "TEMPERATURE",
}
var Sensor_value = map[string]int32{
	"ACCELEROMETER":          1,
	"GYROSCOPE":              4,
	"GYROSCOPE_UNCALIBRATED": 16,
	"LIGHT":                  5,
	"LINEAR_ACCELERATION":    10,
	"PRESSURE":               6,
	"PROXIMITY":              8,
	"RELATIVE_HUMIDITY":      12,
	"STEP_DETECTOR":          18,
	"TEMPERATURE":            7,
}

func (x Sensor) Enum() *Sensor {
	p := new(Sensor)
	*p = x
	return p
}
func (x Sensor) String() string {
	return proto.EnumName(Sensor_name, int32(x))
}
func (x *Sensor) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Sensor_value, data, "Sensor")
	if err != nil {
		return err
	}
	*x = Sensor(value)
	return nil
}

type Gender int32

const (
	Gender_MALE         Gender = 1
	Gender_FEMAIL       Gender = 2
	Gender_THIRD_GENDER Gender = 3
)

var Gender_name = map[int32]string{
	1: "MALE",
	2: "FEMAIL",
	3: "THIRD_GENDER",
}
var Gender_value = map[string]int32{
	"MALE":         1,
	"FEMAIL":       2,
	"THIRD_GENDER": 3,
}

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}
func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (x *Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gender_value, data, "Gender")
	if err != nil {
		return err
	}
	*x = Gender(value)
	return nil
}

type InteractionType int32

const (
	InteractionType_NO_INTERACTION InteractionType = 0
	InteractionType_DOWNLOAD       InteractionType = 2
	InteractionType_DIALING        InteractionType = 3
	InteractionType_MESSAGE        InteractionType = 4
	InteractionType_MAIL           InteractionType = 5
)

var InteractionType_name = map[int32]string{
	0: "NO_INTERACTION",
	2: "DOWNLOAD",
	3: "DIALING",
	4: "MESSAGE",
	5: "MAIL",
}
var InteractionType_value = map[string]int32{
	"NO_INTERACTION": 0,
	"DOWNLOAD":       2,
	"DIALING":        3,
	"MESSAGE":        4,
	"MAIL":           5,
}

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}
func (x InteractionType) String() string {
	return proto.EnumName(InteractionType_name, int32(x))
}
func (x *InteractionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InteractionType_value, data, "InteractionType")
	if err != nil {
		return err
	}
	*x = InteractionType(value)
	return nil
}

type BidRequest struct {
	RequestId        *string   `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ApiVersion       *Version  `protobuf:"bytes,2,req,name=api_version" json:"api_version,omitempty"`
	App              *App      `protobuf:"bytes,3,req,name=app" json:"app,omitempty"`
	Device           *Device   `protobuf:"bytes,4,req,name=device" json:"device,omitempty"`
	Gps              *Gps      `protobuf:"bytes,6,opt,name=gps" json:"gps,omitempty"`
	Content          *Content  `protobuf:"bytes,7,opt,name=content" json:"content,omitempty"`
	User             *User     `protobuf:"bytes,8,opt,name=user" json:"user,omitempty"`
	Adslots          []*AdSlot `protobuf:"bytes,9,rep,name=adslots" json:"adslots,omitempty"`
	IsDebug          *bool     `protobuf:"varint,10,opt,name=is_debug" json:"is_debug,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *BidRequest) Reset()         { *m = BidRequest{} }
func (m *BidRequest) String() string { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()    {}

func (m *BidRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *BidRequest) GetApiVersion() *Version {
	if m != nil {
		return m.ApiVersion
	}
	return nil
}

func (m *BidRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *BidRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *BidRequest) GetGps() *Gps {
	if m != nil {
		return m.Gps
	}
	return nil
}

func (m *BidRequest) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *BidRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BidRequest) GetAdslots() []*AdSlot {
	if m != nil {
		return m.Adslots
	}
	return nil
}

func (m *BidRequest) GetIsDebug() bool {
	if m != nil && m.IsDebug != nil {
		return *m.IsDebug
	}
	return false
}

type App struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}

func (m *App) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type StaticInfo struct {
	BundleId         *string  `protobuf:"bytes,1,req,name=bundle_id" json:"bundle_id,omitempty"`
	Categories       []uint32 `protobuf:"varint,3,rep,name=categories" json:"categories,omitempty"`
	Keywords         []string `protobuf:"bytes,4,rep,name=keywords" json:"keywords,omitempty"`
	HasInAppPurchase *bool    `protobuf:"varint,6,opt,name=has_in_app_purchase" json:"has_in_app_purchase,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StaticInfo) Reset()         { *m = StaticInfo{} }
func (m *StaticInfo) String() string { return proto.CompactTextString(m) }
func (*StaticInfo) ProtoMessage()    {}

func (m *StaticInfo) GetBundleId() string {
	if m != nil && m.BundleId != nil {
		return *m.BundleId
	}
	return ""
}

func (m *StaticInfo) GetCategories() []uint32 {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *StaticInfo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *StaticInfo) GetHasInAppPurchase() bool {
	if m != nil && m.HasInAppPurchase != nil {
		return *m.HasInAppPurchase
	}
	return false
}

type UserPermission struct {
	Type             *Type   `protobuf:"varint,1,req,name=type,enum=main.Type" json:"type,omitempty"`
	Status           *Status `protobuf:"varint,2,req,name=status,enum=main.Status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserPermission) Reset()         { *m = UserPermission{} }
func (m *UserPermission) String() string { return proto.CompactTextString(m) }
func (*UserPermission) ProtoMessage()    {}

func (m *UserPermission) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_ACCESS_FINE_LOCATION
}

func (m *UserPermission) GetStatus() Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Status_UNKNOWN
}

type Device struct {
	Type             *Type    `protobuf:"varint,1,req,name=type,enum=main.Type" json:"type,omitempty"`
	Os               *Os      `protobuf:"varint,2,req,name=os,enum=main.Os" json:"os,omitempty"`
	OsVersion        *Version `protobuf:"bytes,3,req,name=os_version" json:"os_version,omitempty"`
	Vendor           *string  `protobuf:"bytes,4,req,name=vendor" json:"vendor,omitempty"`
	Model            *string  `protobuf:"bytes,5,req,name=model" json:"model,omitempty"`
	Udid             *UdId    `protobuf:"bytes,6,req,name=udid" json:"udid,omitempty"`
	ScreenDensity    *float32 `protobuf:"fixed32,8,opt,name=screen_density" json:"screen_density,omitempty"`
	ScreenSize       *Size    `protobuf:"bytes,9,opt,name=screen_size" json:"screen_size,omitempty"`
	Sensors          []Sensor `protobuf:"varint,10,rep,name=sensors,enum=main.Sensor" json:"sensors,omitempty"`
	IsJailbreaked    *bool    `protobuf:"varint,11,opt,name=is_jailbreaked" json:"is_jailbreaked,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}

func (m *Device) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_ACCESS_FINE_LOCATION
}

func (m *Device) GetOs() Os {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return Os_ANDROID
}

func (m *Device) GetOsVersion() *Version {
	if m != nil {
		return m.OsVersion
	}
	return nil
}

func (m *Device) GetVendor() string {
	if m != nil && m.Vendor != nil {
		return *m.Vendor
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Device) GetUdid() *UdId {
	if m != nil {
		return m.Udid
	}
	return nil
}

func (m *Device) GetScreenDensity() float32 {
	if m != nil && m.ScreenDensity != nil {
		return *m.ScreenDensity
	}
	return 0
}

func (m *Device) GetScreenSize() *Size {
	if m != nil {
		return m.ScreenSize
	}
	return nil
}

func (m *Device) GetSensors() []Sensor {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *Device) GetIsJailbreaked() bool {
	if m != nil && m.IsJailbreaked != nil {
		return *m.IsJailbreaked
	}
	return false
}

type UdId struct {
	Idfa             *string `protobuf:"bytes,1,opt,name=idfa" json:"idfa,omitempty"`
	Imei             *string `protobuf:"bytes,2,opt,name=imei" json:"imei,omitempty"`
	Mac              *string `protobuf:"bytes,3,opt,name=mac" json:"mac,omitempty"`
	Idfv             *string `protobuf:"bytes,4,opt,name=idfv" json:"idfv,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UdId) Reset()         { *m = UdId{} }
func (m *UdId) String() string { return proto.CompactTextString(m) }
func (*UdId) ProtoMessage()    {}

func (m *UdId) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *UdId) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *UdId) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *UdId) GetIdfv() string {
	if m != nil && m.Idfv != nil {
		return *m.Idfv
	}
	return ""
}

type Version struct {
	Major            *uint32 `protobuf:"varint,1,req,name=major" json:"major,omitempty"`
	Minor            *uint32 `protobuf:"varint,2,opt,name=minor,def=0" json:"minor,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}

const Default_Version_Minor uint32 = 0

func (m *Version) GetMajor() uint32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return 0
}

func (m *Version) GetMinor() uint32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return Default_Version_Minor
}

type Gps struct {
	Type             *Type    `protobuf:"varint,1,req,name=type,enum=main.Type" json:"type,omitempty"`
	Longitude        *float64 `protobuf:"fixed64,2,req,name=longitude" json:"longitude,omitempty"`
	Latitude         *float64 `protobuf:"fixed64,3,req,name=latitude" json:"latitude,omitempty"`
	Timestamp        *uint32  `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Gps) Reset()         { *m = Gps{} }
func (m *Gps) String() string { return proto.CompactTextString(m) }
func (*Gps) ProtoMessage()    {}

func (m *Gps) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_ACCESS_FINE_LOCATION
}

func (m *Gps) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *Gps) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Gps) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type User struct {
	Gender           *Gender  `protobuf:"varint,1,opt,name=gender,enum=main.Gender" json:"gender,omitempty"`
	Age              *uint32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Keywords         []string `protobuf:"bytes,3,rep,name=keywords" json:"keywords,omitempty"`
	Meta             []*Meta  `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetGender() Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Gender_MALE
}

func (m *User) GetAge() uint32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *User) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *User) GetMeta() []*Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type AdSlot struct {
	Id                       *string           `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	StaticInfo               *StaticInfo       `protobuf:"bytes,2,opt,name=static_info" json:"static_info,omitempty"`
	Size                     *Size             `protobuf:"bytes,3,req,name=size" json:"size,omitempty"`
	AcceptedInteractionTypes []InteractionType `protobuf:"varint,4,rep,name=accepted_interaction_types,enum=main.InteractionType" json:"accepted_interaction_types,omitempty"`
	ImpressionTime           *uint32           `protobuf:"varint,5,opt,name=impression_time" json:"impression_time,omitempty"`
	XXX_unrecognized         []byte            `json:"-"`
}

func (m *AdSlot) Reset()         { *m = AdSlot{} }
func (m *AdSlot) String() string { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()    {}

func (m *AdSlot) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AdSlot) GetStaticInfo() *StaticInfo {
	if m != nil {
		return m.StaticInfo
	}
	return nil
}

func (m *AdSlot) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *AdSlot) GetAcceptedInteractionTypes() []InteractionType {
	if m != nil {
		return m.AcceptedInteractionTypes
	}
	return nil
}

func (m *AdSlot) GetImpressionTime() uint32 {
	if m != nil && m.ImpressionTime != nil {
		return *m.ImpressionTime
	}
	return 0
}

type Size struct {
	Width            *uint32 `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height           *uint32 `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}

func (m *Size) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Size) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type Content struct {
	Url              *string  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Referer          *string  `protobuf:"bytes,2,opt,name=referer" json:"referer,omitempty"`
	Keywords         []string `protobuf:"bytes,3,rep,name=keywords" json:"keywords,omitempty"`
	Meta             []*Meta  `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}

func (m *Content) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Content) GetReferer() string {
	if m != nil && m.Referer != nil {
		return *m.Referer
	}
	return ""
}

func (m *Content) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *Content) GetMeta() []*Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Meta struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}

func (m *Meta) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Meta) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("main.Type", Type_name, Type_value)
	proto.RegisterEnum("main.Status", Status_name, Status_value)
	proto.RegisterEnum("main.Os", Os_name, Os_value)
	proto.RegisterEnum("main.Orientation", Orientation_name, Orientation_value)
	proto.RegisterEnum("main.Sensor", Sensor_name, Sensor_value)
	proto.RegisterEnum("main.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("main.InteractionType", InteractionType_name, InteractionType_value)
}
