package lib

const STATUS_SUCCESS = 200
const ERROR_NO_AD = 400
const ERROR_ILLEGAL_ADSPACE = 401
const ERROR_NOAD = 405
const ERROR_REQUIRED_FIELD_MISSING = 406
const ERROR_ILLEGAL_SERVER_IP = 407

const ERROR_PARSE_REQUEST = 601
const ERROR_MSGPACK_IMP = 602
const ERROR_INITIAL_FAILED = 603

const ERROR_UNKNON_ERROR = 701
const ERROR_MHSERVER_ERROR = 702
const ERROR_MAP_ERROR = 703
const ERROR_TIMEOUT_ERROR = 704
const ERROR_NO_DEMAND_ERROR = 705
