package lib

const STATUS_SUCCESS = 200
const ERROR_NO_AD = 400
const ERROR_ILLEGAL_ADSPACE = 401
const ERROR_NOAD = 405
const ERROR_REQUIRED_FIELD_MISSING = 406
const ERROR_ILLEGAL_SERVER_IP = 407

const ERROR_PARSE_REQUEST = 601
const ERROR_MSGPACK_IMP = 602
const ERROR_INITIAL_FAILED = 603
const ERROR_CAMPAIGN_DB_ERROR = 604

const ERROR_UNKNON_ERROR = 701
const ERROR_MHSERVER_ERROR = 702
const ERROR_MAP_ERROR = 703
const ERROR_TIMEOUT_ERROR = 704
const ERROR_NO_DEMAND_ERROR = 705
const ERROR_NO_PMP_ADSPACE_ERROR = 706
const ERROR_NO_AD_FROM_QUEUE = 707

const ERROR_BD_MARSHAL_REQ = 800
const ERROR_BD_SERVER = 801
const ERROR_BD_FAILED_RES = 802
const ERROR_BD_MARSHAL_RES = 803

const ADSPACE_STATUS_RUNNING = 0
const ADSPACE_STATUS_STOP = 1

const CREATIVE_TYPE_HTML = 3
