// Code generated by protoc-gen-go.
// source: API_4.1.1.proto
// DO NOT EDIT!

/*
Package mobads_api is a generated protocol buffer package.

It is generated from these files:
	API_4.1.1.proto
	BDService.proto

It has these top-level messages:
	Version
	Size
	Meta
	App
	Gps
	Device
	Network
	Content
	User
	AdSlot
	Ad
	BidRequest
	BidResponse
*/
package mobads_api

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// 创意类型
type CreativeType int32

const (
	CreativeType_TEXT      CreativeType = 1
	CreativeType_IMAGE     CreativeType = 2
	CreativeType_HTML      CreativeType = 3
	CreativeType_VIDEO     CreativeType = 4
	CreativeType_TEXT_ICON CreativeType = 5
)

var CreativeType_name = map[int32]string{
	1: "TEXT",
	2: "IMAGE",
	3: "HTML",
	4: "VIDEO",
	5: "TEXT_ICON",
}
var CreativeType_value = map[string]int32{
	"TEXT":      1,
	"IMAGE":     2,
	"HTML":      3,
	"VIDEO":     4,
	"TEXT_ICON": 5,
}

func (x CreativeType) Enum() *CreativeType {
	p := new(CreativeType)
	*p = x
	return p
}
func (x CreativeType) String() string {
	return proto.EnumName(CreativeType_name, int32(x))
}
func (x *CreativeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CreativeType_value, data, "CreativeType")
	if err != nil {
		return err
	}
	*x = CreativeType(value)
	return nil
}

// 交互类型
type InteractionType int32

const (
	InteractionType_NO_INTERACTION InteractionType = 0
	InteractionType_SURFING        InteractionType = 1
	InteractionType_DOWNLOAD       InteractionType = 2
	InteractionType_DIALING        InteractionType = 3
	InteractionType_MESSAGE        InteractionType = 4
	InteractionType_MAIL           InteractionType = 5
)

var InteractionType_name = map[int32]string{
	0: "NO_INTERACTION",
	1: "SURFING",
	2: "DOWNLOAD",
	3: "DIALING",
	4: "MESSAGE",
	5: "MAIL",
}
var InteractionType_value = map[string]int32{
	"NO_INTERACTION": 0,
	"SURFING":        1,
	"DOWNLOAD":       2,
	"DIALING":        3,
	"MESSAGE":        4,
	"MAIL":           5,
}

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}
func (x InteractionType) String() string {
	return proto.EnumName(InteractionType_name, int32(x))
}
func (x *InteractionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InteractionType_value, data, "InteractionType")
	if err != nil {
		return err
	}
	*x = InteractionType(value)
	return nil
}

// 用户授权类型，这里仅列举目前关心的授权
type App_UserPermission_Type int32

const (
	App_UserPermission_ACCESS_FINE_LOCATION App_UserPermission_Type = 1
	App_UserPermission_CAMERA               App_UserPermission_Type = 2
	App_UserPermission_RECORD_AUDIO         App_UserPermission_Type = 3
)

var App_UserPermission_Type_name = map[int32]string{
	1: "ACCESS_FINE_LOCATION",
	2: "CAMERA",
	3: "RECORD_AUDIO",
}
var App_UserPermission_Type_value = map[string]int32{
	"ACCESS_FINE_LOCATION": 1,
	"CAMERA":               2,
	"RECORD_AUDIO":         3,
}

func (x App_UserPermission_Type) Enum() *App_UserPermission_Type {
	p := new(App_UserPermission_Type)
	*p = x
	return p
}
func (x App_UserPermission_Type) String() string {
	return proto.EnumName(App_UserPermission_Type_name, int32(x))
}
func (x *App_UserPermission_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(App_UserPermission_Type_value, data, "App_UserPermission_Type")
	if err != nil {
		return err
	}
	*x = App_UserPermission_Type(value)
	return nil
}

// 用户授权状态
type App_UserPermission_Status int32

const (
	App_UserPermission_UNKNOWN  App_UserPermission_Status = 0
	App_UserPermission_ACCEPTED App_UserPermission_Status = 1
	App_UserPermission_REFUSED  App_UserPermission_Status = 2
)

var App_UserPermission_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACCEPTED",
	2: "REFUSED",
}
var App_UserPermission_Status_value = map[string]int32{
	"UNKNOWN":  0,
	"ACCEPTED": 1,
	"REFUSED":  2,
}

func (x App_UserPermission_Status) Enum() *App_UserPermission_Status {
	p := new(App_UserPermission_Status)
	*p = x
	return p
}
func (x App_UserPermission_Status) String() string {
	return proto.EnumName(App_UserPermission_Status_name, int32(x))
}
func (x *App_UserPermission_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(App_UserPermission_Status_value, data, "App_UserPermission_Status")
	if err != nil {
		return err
	}
	*x = App_UserPermission_Status(value)
	return nil
}

// GPS坐标类型
type Gps_Type int32

const (
	Gps_WGS84 Gps_Type = 1
	Gps_GCJ02 Gps_Type = 2
	Gps_BD09  Gps_Type = 3
)

var Gps_Type_name = map[int32]string{
	1: "WGS84",
	2: "GCJ02",
	3: "BD09",
}
var Gps_Type_value = map[string]int32{
	"WGS84": 1,
	"GCJ02": 2,
	"BD09":  3,
}

func (x Gps_Type) Enum() *Gps_Type {
	p := new(Gps_Type)
	*p = x
	return p
}
func (x Gps_Type) String() string {
	return proto.EnumName(Gps_Type_name, int32(x))
}
func (x *Gps_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gps_Type_value, data, "Gps_Type")
	if err != nil {
		return err
	}
	*x = Gps_Type(value)
	return nil
}

// 设备类型
type Device_Type int32

const (
	Device_PHONE  Device_Type = 1
	Device_TABLET Device_Type = 2
	Device_TV     Device_Type = 3
)

var Device_Type_name = map[int32]string{
	1: "PHONE",
	2: "TABLET",
	3: "TV",
}
var Device_Type_value = map[string]int32{
	"PHONE":  1,
	"TABLET": 2,
	"TV":     3,
}

func (x Device_Type) Enum() *Device_Type {
	p := new(Device_Type)
	*p = x
	return p
}
func (x Device_Type) String() string {
	return proto.EnumName(Device_Type_name, int32(x))
}
func (x *Device_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_Type_value, data, "Device_Type")
	if err != nil {
		return err
	}
	*x = Device_Type(value)
	return nil
}

// 操作系统类型
type Device_Os int32

const (
	Device_ANDROID Device_Os = 1
	Device_IOS     Device_Os = 2
)

var Device_Os_name = map[int32]string{
	1: "ANDROID",
	2: "IOS",
}
var Device_Os_value = map[string]int32{
	"ANDROID": 1,
	"IOS":     2,
}

func (x Device_Os) Enum() *Device_Os {
	p := new(Device_Os)
	*p = x
	return p
}
func (x Device_Os) String() string {
	return proto.EnumName(Device_Os_name, int32(x))
}
func (x *Device_Os) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_Os_value, data, "Device_Os")
	if err != nil {
		return err
	}
	*x = Device_Os(value)
	return nil
}

// 屏幕方向
type Device_Orientation int32

const (
	Device_LAND Device_Orientation = 1
	Device_PORT Device_Orientation = 2
)

var Device_Orientation_name = map[int32]string{
	1: "LAND",
	2: "PORT",
}
var Device_Orientation_value = map[string]int32{
	"LAND": 1,
	"PORT": 2,
}

func (x Device_Orientation) Enum() *Device_Orientation {
	p := new(Device_Orientation)
	*p = x
	return p
}
func (x Device_Orientation) String() string {
	return proto.EnumName(Device_Orientation_name, int32(x))
}
func (x *Device_Orientation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_Orientation_value, data, "Device_Orientation")
	if err != nil {
		return err
	}
	*x = Device_Orientation(value)
	return nil
}

// 传感器，定义参考http://goo.gl/OTcRN4
type Device_Sensor int32

const (
	Device_ACCELEROMETER               Device_Sensor = 1
	Device_AMBIENT_TEMPERATURE         Device_Sensor = 13
	Device_GAME_ROTATION_VECTOR        Device_Sensor = 15
	Device_GEOMAGNETIC_ROTATION_VECTOR Device_Sensor = 20
	Device_GRAVITY                     Device_Sensor = 9
	Device_GYROSCOPE                   Device_Sensor = 4
	Device_GYROSCOPE_UNCALIBRATED      Device_Sensor = 16
	Device_LIGHT                       Device_Sensor = 5
	Device_LINEAR_ACCELERATION         Device_Sensor = 10
	Device_MAGNETIC_FIELD              Device_Sensor = 2
	Device_MAGNETIC_FIELD_UNCALIBRATED Device_Sensor = 14
	Device_ORIENTATION                 Device_Sensor = 3
	Device_PRESSURE                    Device_Sensor = 6
	Device_PROXIMITY                   Device_Sensor = 8
	Device_RELATIVE_HUMIDITY           Device_Sensor = 12
	Device_ROTATION_VECTOR             Device_Sensor = 11
	Device_SIGNIFICANT_MOTION          Device_Sensor = 17
	Device_STEP_COUNTER                Device_Sensor = 19
	Device_STEP_DETECTOR               Device_Sensor = 18
	Device_TEMPERATURE                 Device_Sensor = 7
)

var Device_Sensor_name = map[int32]string{
	1:  "ACCELEROMETER",
	13: "AMBIENT_TEMPERATURE",
	15: "GAME_ROTATION_VECTOR",
	20: "GEOMAGNETIC_ROTATION_VECTOR",
	9:  "GRAVITY",
	4:  "GYROSCOPE",
	16: "GYROSCOPE_UNCALIBRATED",
	5:  "LIGHT",
	10: "LINEAR_ACCELERATION",
	2:  "MAGNETIC_FIELD",
	14: "MAGNETIC_FIELD_UNCALIBRATED",
	3:  "ORIENTATION",
	6:  "PRESSURE",
	8:  "PROXIMITY",
	12: "RELATIVE_HUMIDITY",
	11: "ROTATION_VECTOR",
	17: "SIGNIFICANT_MOTION",
	19: "STEP_COUNTER",
	18: "STEP_DETECTOR",
	7:  "TEMPERATURE",
}
var Device_Sensor_value = map[string]int32{
	"ACCELEROMETER":               1,
	"AMBIENT_TEMPERATURE":         13,
	"GAME_ROTATION_VECTOR":        15,
	"GEOMAGNETIC_ROTATION_VECTOR": 20,
	"GRAVITY":                     9,
	"GYROSCOPE":                   4,
	"GYROSCOPE_UNCALIBRATED":      16,
	"LIGHT":                       5,
	"LINEAR_ACCELERATION":         10,
	"MAGNETIC_FIELD":              2,
	"MAGNETIC_FIELD_UNCALIBRATED": 14,
	"ORIENTATION":                 3,
	"PRESSURE":                    6,
	"PROXIMITY":                   8,
	"RELATIVE_HUMIDITY":           12,
	"ROTATION_VECTOR":             11,
	"SIGNIFICANT_MOTION":          17,
	"STEP_COUNTER":                19,
	"STEP_DETECTOR":               18,
	"TEMPERATURE":                 7,
}

func (x Device_Sensor) Enum() *Device_Sensor {
	p := new(Device_Sensor)
	*p = x
	return p
}
func (x Device_Sensor) String() string {
	return proto.EnumName(Device_Sensor_name, int32(x))
}
func (x *Device_Sensor) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_Sensor_value, data, "Device_Sensor")
	if err != nil {
		return err
	}
	*x = Device_Sensor(value)
	return nil
}

// 网络类型，定义参考http://goo.gl/WVhKvF，非Android系统自行映射
type Network_Type int32

const (
	Network_BLUETOOTH    Network_Type = 7
	Network_DUMMY        Network_Type = 8
	Network_ETHERNET     Network_Type = 9
	Network_MOBILE       Network_Type = 0
	Network_MOBILE_DUN   Network_Type = 4
	Network_MOBILE_HIPRI Network_Type = 5
	Network_MOBILE_MMS   Network_Type = 2
	Network_MOBILE_SUPL  Network_Type = 3
	Network_WIFI         Network_Type = 1
	Network_WIMAX        Network_Type = 6
	Network_NEW_TYPE     Network_Type = 999
)

var Network_Type_name = map[int32]string{
	7:   "BLUETOOTH",
	8:   "DUMMY",
	9:   "ETHERNET",
	0:   "MOBILE",
	4:   "MOBILE_DUN",
	5:   "MOBILE_HIPRI",
	2:   "MOBILE_MMS",
	3:   "MOBILE_SUPL",
	1:   "WIFI",
	6:   "WIMAX",
	999: "NEW_TYPE",
}
var Network_Type_value = map[string]int32{
	"BLUETOOTH":    7,
	"DUMMY":        8,
	"ETHERNET":     9,
	"MOBILE":       0,
	"MOBILE_DUN":   4,
	"MOBILE_HIPRI": 5,
	"MOBILE_MMS":   2,
	"MOBILE_SUPL":  3,
	"WIFI":         1,
	"WIMAX":        6,
	"NEW_TYPE":     999,
}

func (x Network_Type) Enum() *Network_Type {
	p := new(Network_Type)
	*p = x
	return p
}
func (x Network_Type) String() string {
	return proto.EnumName(Network_Type_name, int32(x))
}
func (x *Network_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_Type_value, data, "Network_Type")
	if err != nil {
		return err
	}
	*x = Network_Type(value)
	return nil
}

// 网络子类，定义参考http://goo.gl/oEGwpP，非Android系统自行映射
type Network_SubType int32

const (
	Network_RTT         Network_SubType = 7
	Network_CDMA        Network_SubType = 4
	Network_EDGE        Network_SubType = 2
	Network_EHRPD       Network_SubType = 14
	Network_EVDO_0      Network_SubType = 5
	Network_EVDO_A      Network_SubType = 6
	Network_EVDO_B      Network_SubType = 12
	Network_GPRS        Network_SubType = 1
	Network_HSDPA       Network_SubType = 8
	Network_HSPA        Network_SubType = 10
	Network_HSPAP       Network_SubType = 15
	Network_HSUPA       Network_SubType = 9
	Network_IDEN        Network_SubType = 11
	Network_LTE         Network_SubType = 13
	Network_UMTS        Network_SubType = 3
	Network_NEW_SUBTYPE Network_SubType = 999
)

var Network_SubType_name = map[int32]string{
	7:   "RTT",
	4:   "CDMA",
	2:   "EDGE",
	14:  "EHRPD",
	5:   "EVDO_0",
	6:   "EVDO_A",
	12:  "EVDO_B",
	1:   "GPRS",
	8:   "HSDPA",
	10:  "HSPA",
	15:  "HSPAP",
	9:   "HSUPA",
	11:  "IDEN",
	13:  "LTE",
	3:   "UMTS",
	999: "NEW_SUBTYPE",
}
var Network_SubType_value = map[string]int32{
	"RTT":         7,
	"CDMA":        4,
	"EDGE":        2,
	"EHRPD":       14,
	"EVDO_0":      5,
	"EVDO_A":      6,
	"EVDO_B":      12,
	"GPRS":        1,
	"HSDPA":       8,
	"HSPA":        10,
	"HSPAP":       15,
	"HSUPA":       9,
	"IDEN":        11,
	"LTE":         13,
	"UMTS":        3,
	"NEW_SUBTYPE": 999,
}

func (x Network_SubType) Enum() *Network_SubType {
	p := new(Network_SubType)
	*p = x
	return p
}
func (x Network_SubType) String() string {
	return proto.EnumName(Network_SubType_name, int32(x))
}
func (x *Network_SubType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_SubType_value, data, "Network_SubType")
	if err != nil {
		return err
	}
	*x = Network_SubType(value)
	return nil
}

// 性别
type User_Gender int32

const (
	User_MALE         User_Gender = 1
	User_FEMAIL       User_Gender = 2
	User_THIRD_GENDER User_Gender = 3
)

var User_Gender_name = map[int32]string{
	1: "MALE",
	2: "FEMAIL",
	3: "THIRD_GENDER",
}
var User_Gender_value = map[string]int32{
	"MALE":         1,
	"FEMAIL":       2,
	"THIRD_GENDER": 3,
}

func (x User_Gender) Enum() *User_Gender {
	p := new(User_Gender)
	*p = x
	return p
}
func (x User_Gender) String() string {
	return proto.EnumName(User_Gender_name, int32(x))
}
func (x *User_Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(User_Gender_value, data, "User_Gender")
	if err != nil {
		return err
	}
	*x = User_Gender(value)
	return nil
}

// 广告位类型
type AdSlot_StaticInfo_Type int32

const (
	AdSlot_StaticInfo_BANNER        AdSlot_StaticInfo_Type = 1
	AdSlot_StaticInfo_INTERSTITIAL  AdSlot_StaticInfo_Type = 2
	AdSlot_StaticInfo_SPLASH        AdSlot_StaticInfo_Type = 3
	AdSlot_StaticInfo_CACHED_SPLASH AdSlot_StaticInfo_Type = 4
	AdSlot_StaticInfo_NEWS_FEED     AdSlot_StaticInfo_Type = 5
)

var AdSlot_StaticInfo_Type_name = map[int32]string{
	1: "BANNER",
	2: "INTERSTITIAL",
	3: "SPLASH",
	4: "CACHED_SPLASH",
	5: "NEWS_FEED",
}
var AdSlot_StaticInfo_Type_value = map[string]int32{
	"BANNER":        1,
	"INTERSTITIAL":  2,
	"SPLASH":        3,
	"CACHED_SPLASH": 4,
	"NEWS_FEED":     5,
}

func (x AdSlot_StaticInfo_Type) Enum() *AdSlot_StaticInfo_Type {
	p := new(AdSlot_StaticInfo_Type)
	*p = x
	return p
}
func (x AdSlot_StaticInfo_Type) String() string {
	return proto.EnumName(AdSlot_StaticInfo_Type_name, int32(x))
}
func (x *AdSlot_StaticInfo_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdSlot_StaticInfo_Type_value, data, "AdSlot_StaticInfo_Type")
	if err != nil {
		return err
	}
	*x = AdSlot_StaticInfo_Type(value)
	return nil
}

// 广告位位置
type AdSlot_StaticInfo_Position int32

const (
	AdSlot_StaticInfo_TOP        AdSlot_StaticInfo_Position = 1
	AdSlot_StaticInfo_BOTTOM     AdSlot_StaticInfo_Position = 2
	AdSlot_StaticInfo_FLOW       AdSlot_StaticInfo_Position = 3
	AdSlot_StaticInfo_MIDDLE     AdSlot_StaticInfo_Position = 4
	AdSlot_StaticInfo_FULLSCREEN AdSlot_StaticInfo_Position = 5
)

var AdSlot_StaticInfo_Position_name = map[int32]string{
	1: "TOP",
	2: "BOTTOM",
	3: "FLOW",
	4: "MIDDLE",
	5: "FULLSCREEN",
}
var AdSlot_StaticInfo_Position_value = map[string]int32{
	"TOP":        1,
	"BOTTOM":     2,
	"FLOW":       3,
	"MIDDLE":     4,
	"FULLSCREEN": 5,
}

func (x AdSlot_StaticInfo_Position) Enum() *AdSlot_StaticInfo_Position {
	p := new(AdSlot_StaticInfo_Position)
	*p = x
	return p
}
func (x AdSlot_StaticInfo_Position) String() string {
	return proto.EnumName(AdSlot_StaticInfo_Position_name, int32(x))
}
func (x *AdSlot_StaticInfo_Position) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdSlot_StaticInfo_Position_value, data, "AdSlot_StaticInfo_Position")
	if err != nil {
		return err
	}
	*x = AdSlot_StaticInfo_Position(value)
	return nil
}

// 广告位填充物料必选素材
type AdSlot_StaticInfo_Asset int32

const (
	AdSlot_StaticInfo_TITLE      AdSlot_StaticInfo_Asset = 1
	AdSlot_StaticInfo_TEXT       AdSlot_StaticInfo_Asset = 2
	AdSlot_StaticInfo_ICON_IMAGE AdSlot_StaticInfo_Asset = 3
	AdSlot_StaticInfo_MAIN_IMAGE AdSlot_StaticInfo_Asset = 4
)

var AdSlot_StaticInfo_Asset_name = map[int32]string{
	1: "TITLE",
	2: "TEXT",
	3: "ICON_IMAGE",
	4: "MAIN_IMAGE",
}
var AdSlot_StaticInfo_Asset_value = map[string]int32{
	"TITLE":      1,
	"TEXT":       2,
	"ICON_IMAGE": 3,
	"MAIN_IMAGE": 4,
}

func (x AdSlot_StaticInfo_Asset) Enum() *AdSlot_StaticInfo_Asset {
	p := new(AdSlot_StaticInfo_Asset)
	*p = x
	return p
}
func (x AdSlot_StaticInfo_Asset) String() string {
	return proto.EnumName(AdSlot_StaticInfo_Asset_name, int32(x))
}
func (x *AdSlot_StaticInfo_Asset) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdSlot_StaticInfo_Asset_value, data, "AdSlot_StaticInfo_Asset")
	if err != nil {
		return err
	}
	*x = AdSlot_StaticInfo_Asset(value)
	return nil
}

// 版本号
type Version struct {
	Major            *uint32 `protobuf:"varint,1,req,name=major" json:"major,omitempty"`
	Minor            *uint32 `protobuf:"varint,2,opt,name=minor,def=0" json:"minor,omitempty"`
	Micro            *uint32 `protobuf:"varint,3,opt,name=micro,def=0" json:"micro,omitempty"`
	Build            *uint32 `protobuf:"varint,4,opt,name=build,def=0" json:"build,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}

const Default_Version_Minor uint32 = 0
const Default_Version_Micro uint32 = 0
const Default_Version_Build uint32 = 0

func (m *Version) GetMajor() uint32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return 0
}

func (m *Version) GetMinor() uint32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return Default_Version_Minor
}

func (m *Version) GetMicro() uint32 {
	if m != nil && m.Micro != nil {
		return *m.Micro
	}
	return Default_Version_Micro
}

func (m *Version) GetBuild() uint32 {
	if m != nil && m.Build != nil {
		return *m.Build
	}
	return Default_Version_Build
}

// 二维尺寸
type Size struct {
	Width            *uint32 `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height           *uint32 `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}

func (m *Size) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Size) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

// 自定义内容元数据
type Meta struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}

func (m *Meta) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Meta) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// 应用信息
type App struct {
	Id               *string               `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	StaticInfo       *App_StaticInfo       `protobuf:"bytes,2,opt,name=static_info" json:"static_info,omitempty"`
	ChannelId        *string               `protobuf:"bytes,3,opt,name=channel_id" json:"channel_id,omitempty"`
	Version          *Version              `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	UserPermission   []*App_UserPermission `protobuf:"bytes,5,rep,name=user_permission" json:"user_permission,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}

func (m *App) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *App) GetStaticInfo() *App_StaticInfo {
	if m != nil {
		return m.StaticInfo
	}
	return nil
}

func (m *App) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *App) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *App) GetUserPermission() []*App_UserPermission {
	if m != nil {
		return m.UserPermission
	}
	return nil
}

// 应用静态信息
type App_StaticInfo struct {
	BundleId         *string  `protobuf:"bytes,1,req,name=bundle_id" json:"bundle_id,omitempty"`
	Name             *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Categories       []uint32 `protobuf:"varint,3,rep,name=categories" json:"categories,omitempty"`
	Keywords         []string `protobuf:"bytes,4,rep,name=keywords" json:"keywords,omitempty"`
	IsPaidApp        *bool    `protobuf:"varint,5,opt,name=is_paid_app" json:"is_paid_app,omitempty"`
	HasInAppPurchase *bool    `protobuf:"varint,6,opt,name=has_in_app_purchase" json:"has_in_app_purchase,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *App_StaticInfo) Reset()         { *m = App_StaticInfo{} }
func (m *App_StaticInfo) String() string { return proto.CompactTextString(m) }
func (*App_StaticInfo) ProtoMessage()    {}

func (m *App_StaticInfo) GetBundleId() string {
	if m != nil && m.BundleId != nil {
		return *m.BundleId
	}
	return ""
}

func (m *App_StaticInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *App_StaticInfo) GetCategories() []uint32 {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *App_StaticInfo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *App_StaticInfo) GetIsPaidApp() bool {
	if m != nil && m.IsPaidApp != nil {
		return *m.IsPaidApp
	}
	return false
}

func (m *App_StaticInfo) GetHasInAppPurchase() bool {
	if m != nil && m.HasInAppPurchase != nil {
		return *m.HasInAppPurchase
	}
	return false
}

// 用户授权信息
type App_UserPermission struct {
	Type             *App_UserPermission_Type   `protobuf:"varint,1,req,name=type,enum=mobads.api.App_UserPermission_Type" json:"type,omitempty"`
	Status           *App_UserPermission_Status `protobuf:"varint,2,req,name=status,enum=mobads.api.App_UserPermission_Status" json:"status,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *App_UserPermission) Reset()         { *m = App_UserPermission{} }
func (m *App_UserPermission) String() string { return proto.CompactTextString(m) }
func (*App_UserPermission) ProtoMessage()    {}

func (m *App_UserPermission) GetType() App_UserPermission_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return App_UserPermission_ACCESS_FINE_LOCATION
}

func (m *App_UserPermission) GetStatus() App_UserPermission_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return App_UserPermission_UNKNOWN
}

// GPS信息
type Gps struct {
	Type             *Gps_Type `protobuf:"varint,1,req,name=type,enum=mobads.api.Gps_Type" json:"type,omitempty"`
	Longitude        *float64  `protobuf:"fixed64,2,req,name=longitude" json:"longitude,omitempty"`
	Latitude         *float64  `protobuf:"fixed64,3,req,name=latitude" json:"latitude,omitempty"`
	Timestamp        *uint32   `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Gps) Reset()         { *m = Gps{} }
func (m *Gps) String() string { return proto.CompactTextString(m) }
func (*Gps) ProtoMessage()    {}

func (m *Gps) GetType() Gps_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Gps_WGS84
}

func (m *Gps) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *Gps) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Gps) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// 设备信息
type Device struct {
	Type             *Device_Type        `protobuf:"varint,1,req,name=type,enum=mobads.api.Device_Type" json:"type,omitempty"`
	Os               *Device_Os          `protobuf:"varint,2,req,name=os,enum=mobads.api.Device_Os" json:"os,omitempty"`
	OsVersion        *Version            `protobuf:"bytes,3,req,name=os_version" json:"os_version,omitempty"`
	Vendor           *string             `protobuf:"bytes,4,req,name=vendor" json:"vendor,omitempty"`
	Model            *string             `protobuf:"bytes,5,req,name=model" json:"model,omitempty"`
	Udid             *Device_UdId        `protobuf:"bytes,6,req,name=udid" json:"udid,omitempty"`
	Orientation      *Device_Orientation `protobuf:"varint,7,opt,name=orientation,enum=mobads.api.Device_Orientation" json:"orientation,omitempty"`
	ScreenDensity    *float32            `protobuf:"fixed32,8,opt,name=screen_density" json:"screen_density,omitempty"`
	ScreenSize       *Size               `protobuf:"bytes,9,opt,name=screen_size" json:"screen_size,omitempty"`
	Sensors          []Device_Sensor     `protobuf:"varint,10,rep,name=sensors,enum=mobads.api.Device_Sensor" json:"sensors,omitempty"`
	IsJailbreaked    *bool               `protobuf:"varint,11,opt,name=is_jailbreaked" json:"is_jailbreaked,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}

func (m *Device) GetType() Device_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Device_PHONE
}

func (m *Device) GetOs() Device_Os {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return Device_ANDROID
}

func (m *Device) GetOsVersion() *Version {
	if m != nil {
		return m.OsVersion
	}
	return nil
}

func (m *Device) GetVendor() string {
	if m != nil && m.Vendor != nil {
		return *m.Vendor
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Device) GetUdid() *Device_UdId {
	if m != nil {
		return m.Udid
	}
	return nil
}

func (m *Device) GetOrientation() Device_Orientation {
	if m != nil && m.Orientation != nil {
		return *m.Orientation
	}
	return Device_LAND
}

func (m *Device) GetScreenDensity() float32 {
	if m != nil && m.ScreenDensity != nil {
		return *m.ScreenDensity
	}
	return 0
}

func (m *Device) GetScreenSize() *Size {
	if m != nil {
		return m.ScreenSize
	}
	return nil
}

func (m *Device) GetSensors() []Device_Sensor {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *Device) GetIsJailbreaked() bool {
	if m != nil && m.IsJailbreaked != nil {
		return *m.IsJailbreaked
	}
	return false
}

// 唯一用户标识，必需使用明文，不可加密，必需按要求填写
type Device_UdId struct {
	Idfa             *string `protobuf:"bytes,1,opt,name=idfa" json:"idfa,omitempty"`
	Imei             *string `protobuf:"bytes,2,opt,name=imei" json:"imei,omitempty"`
	Mac              *string `protobuf:"bytes,3,opt,name=mac" json:"mac,omitempty"`
	Idfv             *string `protobuf:"bytes,4,opt,name=idfv" json:"idfv,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Device_UdId) Reset()         { *m = Device_UdId{} }
func (m *Device_UdId) String() string { return proto.CompactTextString(m) }
func (*Device_UdId) ProtoMessage()    {}

func (m *Device_UdId) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *Device_UdId) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *Device_UdId) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *Device_UdId) GetIdfv() string {
	if m != nil && m.Idfv != nil {
		return *m.Idfv
	}
	return ""
}

// 网络环境信息
type Network struct {
	Ipv4             *string           `protobuf:"bytes,1,opt,name=ipv4" json:"ipv4,omitempty"`
	Ipv6             *string           `protobuf:"bytes,2,opt,name=ipv6" json:"ipv6,omitempty"`
	Type             *Network_Type     `protobuf:"varint,3,opt,name=type,enum=mobads.api.Network_Type" json:"type,omitempty"`
	Subtype          *Network_SubType  `protobuf:"varint,4,opt,name=subtype,enum=mobads.api.Network_SubType" json:"subtype,omitempty"`
	OperatorId       *uint32           `protobuf:"varint,5,opt,name=operator_id" json:"operator_id,omitempty"`
	CellularId       *string           `protobuf:"bytes,6,opt,name=cellular_id" json:"cellular_id,omitempty"`
	WifiAps          []*Network_WiFiAp `protobuf:"bytes,7,rep,name=wifi_aps" json:"wifi_aps,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}

func (m *Network) GetIpv4() string {
	if m != nil && m.Ipv4 != nil {
		return *m.Ipv4
	}
	return ""
}

func (m *Network) GetIpv6() string {
	if m != nil && m.Ipv6 != nil {
		return *m.Ipv6
	}
	return ""
}

func (m *Network) GetType() Network_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Network_BLUETOOTH
}

func (m *Network) GetSubtype() Network_SubType {
	if m != nil && m.Subtype != nil {
		return *m.Subtype
	}
	return Network_RTT
}

func (m *Network) GetOperatorId() uint32 {
	if m != nil && m.OperatorId != nil {
		return *m.OperatorId
	}
	return 0
}

func (m *Network) GetCellularId() string {
	if m != nil && m.CellularId != nil {
		return *m.CellularId
	}
	return ""
}

func (m *Network) GetWifiAps() []*Network_WiFiAp {
	if m != nil {
		return m.WifiAps
	}
	return nil
}

// WiFi热点信息
type Network_WiFiAp struct {
	Mac              *string `protobuf:"bytes,1,req,name=mac" json:"mac,omitempty"`
	Rssi             *int32  `protobuf:"varint,2,req,name=rssi" json:"rssi,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	IsConnected      *bool   `protobuf:"varint,4,opt,name=is_connected" json:"is_connected,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Network_WiFiAp) Reset()         { *m = Network_WiFiAp{} }
func (m *Network_WiFiAp) String() string { return proto.CompactTextString(m) }
func (*Network_WiFiAp) ProtoMessage()    {}

func (m *Network_WiFiAp) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *Network_WiFiAp) GetRssi() int32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *Network_WiFiAp) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Network_WiFiAp) GetIsConnected() bool {
	if m != nil && m.IsConnected != nil {
		return *m.IsConnected
	}
	return false
}

// 内容信息
type Content struct {
	Url              *string  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Referer          *string  `protobuf:"bytes,2,opt,name=referer" json:"referer,omitempty"`
	Keywords         []string `protobuf:"bytes,3,rep,name=keywords" json:"keywords,omitempty"`
	Meta             []*Meta  `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}

func (m *Content) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Content) GetReferer() string {
	if m != nil && m.Referer != nil {
		return *m.Referer
	}
	return ""
}

func (m *Content) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *Content) GetMeta() []*Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 用户个人属性
type User struct {
	Gender           *User_Gender `protobuf:"varint,1,opt,name=gender,enum=mobads.api.User_Gender" json:"gender,omitempty"`
	Age              *uint32      `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Keywords         []string     `protobuf:"bytes,3,rep,name=keywords" json:"keywords,omitempty"`
	Meta             []*Meta      `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetGender() User_Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return User_MALE
}

func (m *User) GetAge() uint32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *User) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *User) GetMeta() []*Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 广告位信息
type AdSlot struct {
	Id                       *string            `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	StaticInfo               *AdSlot_StaticInfo `protobuf:"bytes,2,opt,name=static_info" json:"static_info,omitempty"`
	Size                     *Size              `protobuf:"bytes,3,req,name=size" json:"size,omitempty"`
	AcceptedInteractionTypes []InteractionType  `protobuf:"varint,4,rep,name=accepted_interaction_types,enum=mobads.api.InteractionType" json:"accepted_interaction_types,omitempty"`
	ImpressionTime           *uint32            `protobuf:"varint,5,opt,name=impression_time" json:"impression_time,omitempty"`
	XXX_unrecognized         []byte             `json:"-"`
}

func (m *AdSlot) Reset()         { *m = AdSlot{} }
func (m *AdSlot) String() string { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()    {}

func (m *AdSlot) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AdSlot) GetStaticInfo() *AdSlot_StaticInfo {
	if m != nil {
		return m.StaticInfo
	}
	return nil
}

func (m *AdSlot) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *AdSlot) GetAcceptedInteractionTypes() []InteractionType {
	if m != nil {
		return m.AcceptedInteractionTypes
	}
	return nil
}

func (m *AdSlot) GetImpressionTime() uint32 {
	if m != nil && m.ImpressionTime != nil {
		return *m.ImpressionTime
	}
	return 0
}

// 广告位静态信息
type AdSlot_StaticInfo struct {
	Type                  *AdSlot_StaticInfo_Type     `protobuf:"varint,1,req,name=type,enum=mobads.api.AdSlot_StaticInfo_Type" json:"type,omitempty"`
	AcceptedCreativeTypes []CreativeType              `protobuf:"varint,2,rep,name=accepted_creative_types,enum=mobads.api.CreativeType" json:"accepted_creative_types,omitempty"`
	Position              *AdSlot_StaticInfo_Position `protobuf:"varint,3,opt,name=position,enum=mobads.api.AdSlot_StaticInfo_Position" json:"position,omitempty"`
	MinimunCpm            *float32                    `protobuf:"fixed32,4,opt,name=minimun_cpm" json:"minimun_cpm,omitempty"`
	PreferedBuyers        []*AdSlot_StaticInfo_Buyer  `protobuf:"bytes,5,rep,name=prefered_buyers" json:"prefered_buyers,omitempty"`
	ExclusiveBuyers       []uint32                    `protobuf:"varint,6,rep,name=exclusive_buyers" json:"exclusive_buyers,omitempty"`
	AllowAllBuyers        *bool                       `protobuf:"varint,7,opt,name=allow_all_buyers" json:"allow_all_buyers,omitempty"`
	ExclusiveAdCategories []uint32                    `protobuf:"varint,8,rep,name=exclusive_ad_categories" json:"exclusive_ad_categories,omitempty"`
	OpenInternalBrowser   *bool                       `protobuf:"varint,9,opt,name=open_internal_browser" json:"open_internal_browser,omitempty"`
	Asset                 []AdSlot_StaticInfo_Asset   `protobuf:"varint,10,rep,name=asset,enum=mobads.api.AdSlot_StaticInfo_Asset" json:"asset,omitempty"`
	XXX_unrecognized      []byte                      `json:"-"`
}

func (m *AdSlot_StaticInfo) Reset()         { *m = AdSlot_StaticInfo{} }
func (m *AdSlot_StaticInfo) String() string { return proto.CompactTextString(m) }
func (*AdSlot_StaticInfo) ProtoMessage()    {}

func (m *AdSlot_StaticInfo) GetType() AdSlot_StaticInfo_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return AdSlot_StaticInfo_BANNER
}

func (m *AdSlot_StaticInfo) GetAcceptedCreativeTypes() []CreativeType {
	if m != nil {
		return m.AcceptedCreativeTypes
	}
	return nil
}

func (m *AdSlot_StaticInfo) GetPosition() AdSlot_StaticInfo_Position {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return AdSlot_StaticInfo_TOP
}

func (m *AdSlot_StaticInfo) GetMinimunCpm() float32 {
	if m != nil && m.MinimunCpm != nil {
		return *m.MinimunCpm
	}
	return 0
}

func (m *AdSlot_StaticInfo) GetPreferedBuyers() []*AdSlot_StaticInfo_Buyer {
	if m != nil {
		return m.PreferedBuyers
	}
	return nil
}

func (m *AdSlot_StaticInfo) GetExclusiveBuyers() []uint32 {
	if m != nil {
		return m.ExclusiveBuyers
	}
	return nil
}

func (m *AdSlot_StaticInfo) GetAllowAllBuyers() bool {
	if m != nil && m.AllowAllBuyers != nil {
		return *m.AllowAllBuyers
	}
	return false
}

func (m *AdSlot_StaticInfo) GetExclusiveAdCategories() []uint32 {
	if m != nil {
		return m.ExclusiveAdCategories
	}
	return nil
}

func (m *AdSlot_StaticInfo) GetOpenInternalBrowser() bool {
	if m != nil && m.OpenInternalBrowser != nil {
		return *m.OpenInternalBrowser
	}
	return false
}

func (m *AdSlot_StaticInfo) GetAsset() []AdSlot_StaticInfo_Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

type AdSlot_StaticInfo_Buyer struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	MinimunCpm       *uint32 `protobuf:"varint,2,opt,name=minimun_cpm" json:"minimun_cpm,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AdSlot_StaticInfo_Buyer) Reset()         { *m = AdSlot_StaticInfo_Buyer{} }
func (m *AdSlot_StaticInfo_Buyer) String() string { return proto.CompactTextString(m) }
func (*AdSlot_StaticInfo_Buyer) ProtoMessage()    {}

func (m *AdSlot_StaticInfo_Buyer) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *AdSlot_StaticInfo_Buyer) GetMinimunCpm() uint32 {
	if m != nil && m.MinimunCpm != nil {
		return *m.MinimunCpm
	}
	return 0
}

// 广告
type Ad struct {
	AdslotId         *string          `protobuf:"bytes,1,opt,name=adslot_id" json:"adslot_id,omitempty"`
	BuyerId          *uint32          `protobuf:"varint,2,opt,name=buyer_id" json:"buyer_id,omitempty"`
	AdId             *uint32          `protobuf:"varint,3,opt,name=ad_id" json:"ad_id,omitempty"`
	HtmlSnippet      *string          `protobuf:"bytes,4,opt,name=html_snippet" json:"html_snippet,omitempty"`
	MaterialMeta     *Ad_MaterialMeta `protobuf:"bytes,5,opt,name=material_meta" json:"material_meta,omitempty"`
	ImpressionTime   *uint32          `protobuf:"varint,6,opt,name=impression_time" json:"impression_time,omitempty"`
	TargetedHours    *uint32          `protobuf:"varint,7,opt,name=targeted_hours" json:"targeted_hours,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}

func (m *Ad) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *Ad) GetBuyerId() uint32 {
	if m != nil && m.BuyerId != nil {
		return *m.BuyerId
	}
	return 0
}

func (m *Ad) GetAdId() uint32 {
	if m != nil && m.AdId != nil {
		return *m.AdId
	}
	return 0
}

func (m *Ad) GetHtmlSnippet() string {
	if m != nil && m.HtmlSnippet != nil {
		return *m.HtmlSnippet
	}
	return ""
}

func (m *Ad) GetMaterialMeta() *Ad_MaterialMeta {
	if m != nil {
		return m.MaterialMeta
	}
	return nil
}

func (m *Ad) GetImpressionTime() uint32 {
	if m != nil && m.ImpressionTime != nil {
		return *m.ImpressionTime
	}
	return 0
}

func (m *Ad) GetTargetedHours() uint32 {
	if m != nil && m.TargetedHours != nil {
		return *m.TargetedHours
	}
	return 0
}

// 广告物料元数据
type Ad_MaterialMeta struct {
	CreativeType     *CreativeType    `protobuf:"varint,1,req,name=creative_type,enum=mobads.api.CreativeType" json:"creative_type,omitempty"`
	InteractionType  *InteractionType `protobuf:"varint,2,req,name=interaction_type,enum=mobads.api.InteractionType" json:"interaction_type,omitempty"`
	WinNoticeUrl     []string         `protobuf:"bytes,3,rep,name=win_notice_url" json:"win_notice_url,omitempty"`
	Title            *string          `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Description1     *string          `protobuf:"bytes,5,opt,name=description1" json:"description1,omitempty"`
	Description2     *string          `protobuf:"bytes,6,opt,name=description2" json:"description2,omitempty"`
	MediaUrl         *string          `protobuf:"bytes,7,opt,name=media_url" json:"media_url,omitempty"`
	ShowUrl          *string          `protobuf:"bytes,8,opt,name=show_url" json:"show_url,omitempty"`
	ClickUrl         *string          `protobuf:"bytes,9,opt,name=click_url" json:"click_url,omitempty"`
	IconUrl          *string          `protobuf:"bytes,10,opt,name=icon_url" json:"icon_url,omitempty"`
	CachedUrl        []string         `protobuf:"bytes,12,rep,name=cached_url" json:"cached_url,omitempty"`
	Name             *string          `protobuf:"bytes,13,opt,name=name" json:"name,omitempty"`
	MediaHeight      *uint32          `protobuf:"varint,15,opt,name=media_height" json:"media_height,omitempty"`
	MediaWidth       *uint32          `protobuf:"varint,16,opt,name=media_width" json:"media_width,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Ad_MaterialMeta) Reset()         { *m = Ad_MaterialMeta{} }
func (m *Ad_MaterialMeta) String() string { return proto.CompactTextString(m) }
func (*Ad_MaterialMeta) ProtoMessage()    {}

func (m *Ad_MaterialMeta) GetCreativeType() CreativeType {
	if m != nil && m.CreativeType != nil {
		return *m.CreativeType
	}
	return CreativeType_TEXT
}

func (m *Ad_MaterialMeta) GetInteractionType() InteractionType {
	if m != nil && m.InteractionType != nil {
		return *m.InteractionType
	}
	return InteractionType_NO_INTERACTION
}

func (m *Ad_MaterialMeta) GetWinNoticeUrl() []string {
	if m != nil {
		return m.WinNoticeUrl
	}
	return nil
}

func (m *Ad_MaterialMeta) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Ad_MaterialMeta) GetDescription1() string {
	if m != nil && m.Description1 != nil {
		return *m.Description1
	}
	return ""
}

func (m *Ad_MaterialMeta) GetDescription2() string {
	if m != nil && m.Description2 != nil {
		return *m.Description2
	}
	return ""
}

func (m *Ad_MaterialMeta) GetMediaUrl() string {
	if m != nil && m.MediaUrl != nil {
		return *m.MediaUrl
	}
	return ""
}

func (m *Ad_MaterialMeta) GetShowUrl() string {
	if m != nil && m.ShowUrl != nil {
		return *m.ShowUrl
	}
	return ""
}

func (m *Ad_MaterialMeta) GetClickUrl() string {
	if m != nil && m.ClickUrl != nil {
		return *m.ClickUrl
	}
	return ""
}

func (m *Ad_MaterialMeta) GetIconUrl() string {
	if m != nil && m.IconUrl != nil {
		return *m.IconUrl
	}
	return ""
}

func (m *Ad_MaterialMeta) GetCachedUrl() []string {
	if m != nil {
		return m.CachedUrl
	}
	return nil
}

func (m *Ad_MaterialMeta) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Ad_MaterialMeta) GetMediaHeight() uint32 {
	if m != nil && m.MediaHeight != nil {
		return *m.MediaHeight
	}
	return 0
}

func (m *Ad_MaterialMeta) GetMediaWidth() uint32 {
	if m != nil && m.MediaWidth != nil {
		return *m.MediaWidth
	}
	return 0
}

// 竞价请求
type BidRequest struct {
	RequestId        *string   `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	ApiVersion       *Version  `protobuf:"bytes,2,req,name=api_version" json:"api_version,omitempty"`
	App              *App      `protobuf:"bytes,3,req,name=app" json:"app,omitempty"`
	Device           *Device   `protobuf:"bytes,4,req,name=device" json:"device,omitempty"`
	Network          *Network  `protobuf:"bytes,5,req,name=network" json:"network,omitempty"`
	Gps              *Gps      `protobuf:"bytes,6,opt,name=gps" json:"gps,omitempty"`
	Content          *Content  `protobuf:"bytes,7,opt,name=content" json:"content,omitempty"`
	User             *User     `protobuf:"bytes,8,opt,name=user" json:"user,omitempty"`
	Adslots          []*AdSlot `protobuf:"bytes,9,rep,name=adslots" json:"adslots,omitempty"`
	IsDebug          *bool     `protobuf:"varint,10,opt,name=is_debug,def=0" json:"is_debug,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *BidRequest) Reset()         { *m = BidRequest{} }
func (m *BidRequest) String() string { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()    {}

const Default_BidRequest_IsDebug bool = false

func (m *BidRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *BidRequest) GetApiVersion() *Version {
	if m != nil {
		return m.ApiVersion
	}
	return nil
}

func (m *BidRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *BidRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *BidRequest) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *BidRequest) GetGps() *Gps {
	if m != nil {
		return m.Gps
	}
	return nil
}

func (m *BidRequest) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *BidRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BidRequest) GetAdslots() []*AdSlot {
	if m != nil {
		return m.Adslots
	}
	return nil
}

func (m *BidRequest) GetIsDebug() bool {
	if m != nil && m.IsDebug != nil {
		return *m.IsDebug
	}
	return Default_BidRequest_IsDebug
}

// 竞价应答
type BidResponse struct {
	RequestId        *string `protobuf:"bytes,1,req,name=request_id" json:"request_id,omitempty"`
	Ads              []*Ad   `protobuf:"bytes,2,rep,name=ads" json:"ads,omitempty"`
	ErrorCode        *uint64 `protobuf:"varint,3,opt,name=error_code" json:"error_code,omitempty"`
	ExpirationTime   *uint32 `protobuf:"varint,4,opt,name=expiration_time" json:"expiration_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidResponse) Reset()         { *m = BidResponse{} }
func (m *BidResponse) String() string { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()    {}

func (m *BidResponse) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *BidResponse) GetAds() []*Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *BidResponse) GetErrorCode() uint64 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *BidResponse) GetExpirationTime() uint32 {
	if m != nil && m.ExpirationTime != nil {
		return *m.ExpirationTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("mobads.api.CreativeType", CreativeType_name, CreativeType_value)
	proto.RegisterEnum("mobads.api.InteractionType", InteractionType_name, InteractionType_value)
	proto.RegisterEnum("mobads.api.App_UserPermission_Type", App_UserPermission_Type_name, App_UserPermission_Type_value)
	proto.RegisterEnum("mobads.api.App_UserPermission_Status", App_UserPermission_Status_name, App_UserPermission_Status_value)
	proto.RegisterEnum("mobads.api.Gps_Type", Gps_Type_name, Gps_Type_value)
	proto.RegisterEnum("mobads.api.Device_Type", Device_Type_name, Device_Type_value)
	proto.RegisterEnum("mobads.api.Device_Os", Device_Os_name, Device_Os_value)
	proto.RegisterEnum("mobads.api.Device_Orientation", Device_Orientation_name, Device_Orientation_value)
	proto.RegisterEnum("mobads.api.Device_Sensor", Device_Sensor_name, Device_Sensor_value)
	proto.RegisterEnum("mobads.api.Network_Type", Network_Type_name, Network_Type_value)
	proto.RegisterEnum("mobads.api.Network_SubType", Network_SubType_name, Network_SubType_value)
	proto.RegisterEnum("mobads.api.User_Gender", User_Gender_name, User_Gender_value)
	proto.RegisterEnum("mobads.api.AdSlot_StaticInfo_Type", AdSlot_StaticInfo_Type_name, AdSlot_StaticInfo_Type_value)
	proto.RegisterEnum("mobads.api.AdSlot_StaticInfo_Position", AdSlot_StaticInfo_Position_name, AdSlot_StaticInfo_Position_value)
	proto.RegisterEnum("mobads.api.AdSlot_StaticInfo_Asset", AdSlot_StaticInfo_Asset_name, AdSlot_StaticInfo_Asset_value)
}
