// Code generated by protoc-gen-go.
// source: BDService.proto
// DO NOT EDIT!

package mobads_api

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf
